# Generated by Django 2.2.4 on 2019-08-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='applience',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Type'),
        ),
    ]
