# Generated by Django 2.2.4 on 2019-08-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_applience_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applience',
            old_name='type',
            new_name='type_of_applience_id',
        ),
    ]
