# Generated by Django 2.2.4 on 2019-08-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190827_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applience',
            old_name='type_of_applience_id',
            new_name='type_of_applience',
        ),
    ]
