# Generated by Django 2.2.4 on 2019-08-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190827_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applience',
            old_name='type_of_applience',
            new_name='typeofapplience',
        ),
    ]
