# Generated by Django 2.2.4 on 2019-08-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190827_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='applience',
            name='abduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Abduction'),
        ),
        migrations.AddField(
            model_name='applience',
            name='bringing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Bringing'),
        ),
        migrations.AddField(
            model_name='applience',
            name='repair',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Repair'),
        ),
        migrations.AddField(
            model_name='people',
            name='abduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Abduction'),
        ),
        migrations.AddField(
            model_name='people',
            name='bringing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Bringing'),
        ),
        migrations.AddField(
            model_name='people',
            name='repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Repair'),
        ),
    ]
